#!/usr/bin/env python3

import sys
import socket

if len(sys.argv) != 3:
    sys.stderr.write("usage: %s in.hosts out.csv\n" % sys.argv[0])
    exit(1)

keys = []
lines = {}

with open(sys.argv[1], 'r') as inf:
    for line in inf:
        row = line.split()
        keys.append(row[0])
        lines[row[0]] = [entry[-1][0] for entry in
                socket.getaddrinfo(row[1], None, family=socket.AF_INET, type=socket.SOCK_DGRAM)]

def sortfn(ip_str):
    ip = socket.inet_aton(ip_str)
    return ip[3:4] + ip[0:3]

with open(sys.argv[2], 'w') as outf:
    for key in sorted(keys, key=sortfn):
        for val in lines[key]:
            outf.write("%s,%s\n" % (key, val))
